/*
 * php-constants.cpp
 *
 * This file is a part of php-git2.
 */

#include "php-git2.h"
using namespace php_git2;

// Simplify constant registration.

#define PHP_GIT2_CONSTANT(name) \
    REGISTER_LONG_CONSTANT(#name,name,CONST_CS|CONST_PERSISTENT)

void php_git2::php_git2_register_constants(int module_number TSRMLS_DC)
{
    // GIT_*
    PHP_GIT2_CONSTANT(GIT_OK);
    PHP_GIT2_CONSTANT(GIT_ERROR);
    PHP_GIT2_CONSTANT(GIT_ENOTFOUND);
    PHP_GIT2_CONSTANT(GIT_EEXISTS);
    PHP_GIT2_CONSTANT(GIT_EAMBIGUOUS);
    PHP_GIT2_CONSTANT(GIT_EBUFS);
    PHP_GIT2_CONSTANT(GIT_EUSER);
    PHP_GIT2_CONSTANT(GIT_EBAREREPO);
    PHP_GIT2_CONSTANT(GIT_EUNBORNBRANCH);
    PHP_GIT2_CONSTANT(GIT_EUNMERGED);
    PHP_GIT2_CONSTANT(GIT_ENONFASTFORWARD);
    PHP_GIT2_CONSTANT(GIT_EINVALIDSPEC);
    PHP_GIT2_CONSTANT(GIT_ECONFLICT);
    PHP_GIT2_CONSTANT(GIT_ELOCKED);
    PHP_GIT2_CONSTANT(GIT_EMODIFIED);
    PHP_GIT2_CONSTANT(GIT_EAUTH);
    PHP_GIT2_CONSTANT(GIT_ECERTIFICATE);
    PHP_GIT2_CONSTANT(GIT_EAPPLIED);
    PHP_GIT2_CONSTANT(GIT_EPEEL);
    PHP_GIT2_CONSTANT(GIT_EEOF);
    PHP_GIT2_CONSTANT(GIT_EINVALID);
    PHP_GIT2_CONSTANT(GIT_EUNCOMMITTED);
    PHP_GIT2_CONSTANT(GIT_EDIRECTORY);
    PHP_GIT2_CONSTANT(GIT_EMERGECONFLICT);
    PHP_GIT2_CONSTANT(GIT_PASSTHROUGH);
    PHP_GIT2_CONSTANT(GIT_ITEROVER);

    // GIT_FEATURE_*
    PHP_GIT2_CONSTANT(GIT_FEATURE_THREADS);
    PHP_GIT2_CONSTANT(GIT_FEATURE_HTTPS);
    PHP_GIT2_CONSTANT(GIT_FEATURE_SSH);
    PHP_GIT2_CONSTANT(GIT_FEATURE_NSEC);

    // GIT_OBJ_*
    PHP_GIT2_CONSTANT(GIT_OBJ_ANY);
    PHP_GIT2_CONSTANT(GIT_OBJ_BAD);
    PHP_GIT2_CONSTANT(GIT_OBJ__EXT1);
    PHP_GIT2_CONSTANT(GIT_OBJ_COMMIT);
    PHP_GIT2_CONSTANT(GIT_OBJ_TREE);
    PHP_GIT2_CONSTANT(GIT_OBJ_BLOB);
    PHP_GIT2_CONSTANT(GIT_OBJ_TAG);
    PHP_GIT2_CONSTANT(GIT_OBJ__EXT2);
    PHP_GIT2_CONSTANT(GIT_OBJ_OFS_DELTA);
    PHP_GIT2_CONSTANT(GIT_OBJ_REF_DELTA);

    // GIT_SORT_*
    PHP_GIT2_CONSTANT(GIT_SORT_NONE);
    PHP_GIT2_CONSTANT(GIT_SORT_TOPOLOGICAL);
    PHP_GIT2_CONSTANT(GIT_SORT_TIME);
    PHP_GIT2_CONSTANT(GIT_SORT_REVERSE);

    // GIT_PATH_LIST_SEPARATOR
    PHP_GIT2_CONSTANT(GIT_PATH_LIST_SEPARATOR);

    // GIT_FILEMODE_*
    PHP_GIT2_CONSTANT(GIT_FILEMODE_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_TREE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_BLOB);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_BLOB_EXECUTABLE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_LINK);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_COMMIT);

    // GIT_TREEWALK_*
    PHP_GIT2_CONSTANT(GIT_TREEWALK_PRE);
    PHP_GIT2_CONSTANT(GIT_TREEWALK_POST);

    // GIT_BLAME_*
    PHP_GIT2_CONSTANT(GIT_BLAME_NORMAL);
    PHP_GIT2_CONSTANT(GIT_BLAME_TRACK_COPIES_SAME_FILE);
    PHP_GIT2_CONSTANT(GIT_BLAME_TRACK_COPIES_SAME_COMMIT_MOVES);
    PHP_GIT2_CONSTANT(GIT_BLAME_TRACK_COPIES_SAME_COMMIT_COPIES);
    PHP_GIT2_CONSTANT(GIT_BLAME_TRACK_COPIES_ANY_COMMIT_COPIES);
    PHP_GIT2_CONSTANT(GIT_BLAME_FIRST_PARENT);
    PHP_GIT2_CONSTANT(GIT_BLAME_OPTIONS_VERSION);

    // GIT_REVPARSE_*
    PHP_GIT2_CONSTANT(GIT_REVPARSE_SINGLE);
    PHP_GIT2_CONSTANT(GIT_REVPARSE_RANGE);
    PHP_GIT2_CONSTANT(GIT_REVPARSE_MERGE_BASE);

    // GIT_BRANCH_*
    PHP_GIT2_CONSTANT(GIT_BRANCH_LOCAL);
    PHP_GIT2_CONSTANT(GIT_BRANCH_REMOTE);
    PHP_GIT2_CONSTANT(GIT_BRANCH_ALL);

    // GIT_REF_FORMAT_*
    PHP_GIT2_CONSTANT(GIT_REF_FORMAT_NORMAL);
    PHP_GIT2_CONSTANT(GIT_REF_FORMAT_ALLOW_ONELEVEL);
    PHP_GIT2_CONSTANT(GIT_REF_FORMAT_REFSPEC_PATTERN);
    PHP_GIT2_CONSTANT(GIT_REF_FORMAT_REFSPEC_SHORTHAND);

    // GIT_REF_*
    PHP_GIT2_CONSTANT(GIT_REF_INVALID);
    PHP_GIT2_CONSTANT(GIT_REF_OID);
    PHP_GIT2_CONSTANT(GIT_REF_SYMBOLIC);
    PHP_GIT2_CONSTANT(GIT_REF_LISTALL);

    // GIT_REPOSITORY_INIT_*
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_BARE);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_NO_REINIT);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_NO_DOTGIT_DIR);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_MKDIR);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_MKPATH);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_RELATIVE_GITLINK);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_SHARED_UMASK);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_SHARED_GROUP);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_INIT_SHARED_ALL);

    // GIT_REPOSITORY_OPEN_*
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_OPEN_NO_SEARCH);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_OPEN_CROSS_FS);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_OPEN_BARE);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_OPEN_NO_DOTGIT);
    PHP_GIT2_CONSTANT(GIT_REPOSITORY_OPEN_FROM_ENV);

    // GIT_CONFIG_*
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_PROGRAMDATA);
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_SYSTEM);
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_XDG);
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_GLOBAL);
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_LOCAL);
    PHP_GIT2_CONSTANT(GIT_CONFIG_LEVEL_APP);
    PHP_GIT2_CONSTANT(GIT_CONFIG_HIGHEST_LEVEL);

    // GIT_CLONE_LOCAL_*
    PHP_GIT2_CONSTANT(GIT_CLONE_LOCAL_AUTO);
    PHP_GIT2_CONSTANT(GIT_CLONE_LOCAL);
    PHP_GIT2_CONSTANT(GIT_CLONE_NO_LOCAL);
    PHP_GIT2_CONSTANT(GIT_CLONE_LOCAL_NO_LINKS);
    PHP_GIT2_CONSTANT(GIT_CLONE_OPTIONS_VERSION);

    // GIT_CHECKOUT_*
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_ALLOW_CONFLICTS);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_CONFLICT_STYLE_DIFF3);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_CONFLICT_STYLE_MERGE);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_DONT_OVERWRITE_IGNORED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_DONT_REMOVE_EXISTING);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_DONT_UPDATE_INDEX);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_DONT_WRITE_INDEX);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_FORCE);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NONE);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NO_REFRESH);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_ALL);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_CONFLICT);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_DIRTY);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_IGNORED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_NONE);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_NOTIFY_UPDATED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_OPTIONS_VERSION);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_RECREATE_MISSING);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_REMOVE_IGNORED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_REMOVE_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_SAFE);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_SKIP_LOCKED_DIRECTORIES);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_SKIP_UNMERGED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_UPDATE_ONLY);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_UPDATE_SUBMODULES);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_UPDATE_SUBMODULES_IF_CHANGED);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_USE_OURS);
    PHP_GIT2_CONSTANT(GIT_CHECKOUT_USE_THEIRS);

    // GIT_CVAR_*
    PHP_GIT2_CONSTANT(GIT_CVAR_FALSE);
    PHP_GIT2_CONSTANT(GIT_CVAR_TRUE);
    PHP_GIT2_CONSTANT(GIT_CVAR_INT32);
    PHP_GIT2_CONSTANT(GIT_CVAR_STRING);

    // GIT_DIFF_*
    PHP_GIT2_CONSTANT(GIT_DIFF_NORMAL);
    PHP_GIT2_CONSTANT(GIT_DIFF_REVERSE);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_IGNORED);
    PHP_GIT2_CONSTANT(GIT_DIFF_RECURSE_IGNORED_DIRS);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_DIFF_RECURSE_UNTRACKED_DIRS);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_UNMODIFIED);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_TYPECHANGE);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_TYPECHANGE_TREES);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_FILEMODE);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_SUBMODULES);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_CASE);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_CASECHANGE);
    PHP_GIT2_CONSTANT(GIT_DIFF_DISABLE_PATHSPEC_MATCH);
    PHP_GIT2_CONSTANT(GIT_DIFF_SKIP_BINARY_CHECK);
    PHP_GIT2_CONSTANT(GIT_DIFF_ENABLE_FAST_UNTRACKED_DIRS);
    PHP_GIT2_CONSTANT(GIT_DIFF_UPDATE_INDEX);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_DIFF_INCLUDE_UNREADABLE_AS_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORCE_TEXT);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORCE_BINARY);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_WHITESPACE);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_WHITESPACE_CHANGE);
    PHP_GIT2_CONSTANT(GIT_DIFF_IGNORE_WHITESPACE_EOL);
    PHP_GIT2_CONSTANT(GIT_DIFF_SHOW_UNTRACKED_CONTENT);
    PHP_GIT2_CONSTANT(GIT_DIFF_SHOW_UNMODIFIED);
    PHP_GIT2_CONSTANT(GIT_DIFF_PATIENCE);
    PHP_GIT2_CONSTANT(GIT_DIFF_MINIMAL);
    PHP_GIT2_CONSTANT(GIT_DIFF_SHOW_BINARY);

    // GIT_DIFF_BINARY_*
    PHP_GIT2_CONSTANT(GIT_DIFF_BINARY_NONE);
    PHP_GIT2_CONSTANT(GIT_DIFF_BINARY_LITERAL);
    PHP_GIT2_CONSTANT(GIT_DIFF_BINARY_DELTA);

    // GIT_DIFF_LINE_*
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_CONTEXT);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_ADDITION);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_DELETION);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_CONTEXT_EOFNL);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_ADD_EOFNL);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_DEL_EOFNL);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_FILE_HDR);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_HUNK_HDR);
    PHP_GIT2_CONSTANT(GIT_DIFF_LINE_BINARY);

    // GIT_DIFF_FORMAT_EMAIL_*
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_EMAIL_NONE);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_EMAIL_EXCLUDE_SUBJECT_PATCH_MARKER);

    // GIT_DIFF_FORMAT_*
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_PATCH);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_PATCH_HEADER);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_RAW);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_NAME_ONLY);
    PHP_GIT2_CONSTANT(GIT_DIFF_FORMAT_NAME_STATUS);

    // GIT_DIFF_STATS_*
    PHP_GIT2_CONSTANT(GIT_DIFF_STATS_NONE);
    PHP_GIT2_CONSTANT(GIT_DIFF_STATS_FULL);
    PHP_GIT2_CONSTANT(GIT_DIFF_STATS_SHORT);
    PHP_GIT2_CONSTANT(GIT_DIFF_STATS_NUMBER);
    PHP_GIT2_CONSTANT(GIT_DIFF_STATS_INCLUDE_SUMMARY);

    // GIT_DELTA_*
    PHP_GIT2_CONSTANT(GIT_DELTA_UNMODIFIED);
    PHP_GIT2_CONSTANT(GIT_DELTA_ADDED);
    PHP_GIT2_CONSTANT(GIT_DELTA_DELETED);
    PHP_GIT2_CONSTANT(GIT_DELTA_MODIFIED);
    PHP_GIT2_CONSTANT(GIT_DELTA_RENAMED);
    PHP_GIT2_CONSTANT(GIT_DELTA_COPIED);
    PHP_GIT2_CONSTANT(GIT_DELTA_IGNORED);
    PHP_GIT2_CONSTANT(GIT_DELTA_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_DELTA_TYPECHANGE);
    PHP_GIT2_CONSTANT(GIT_DELTA_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_DELTA_CONFLICTED);

    // GIT_SUBMODULE_IGNORE_*
    PHP_GIT2_CONSTANT(GIT_SUBMODULE_IGNORE_UNSPECIFIED);
    PHP_GIT2_CONSTANT(GIT_SUBMODULE_IGNORE_NONE);
    PHP_GIT2_CONSTANT(GIT_SUBMODULE_IGNORE_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_SUBMODULE_IGNORE_DIRTY);
    PHP_GIT2_CONSTANT(GIT_SUBMODULE_IGNORE_ALL);

    // GIT_INDEXCAP_*
    PHP_GIT2_CONSTANT(GIT_INDEXCAP_IGNORE_CASE);
    PHP_GIT2_CONSTANT(GIT_INDEXCAP_NO_FILEMODE);
    PHP_GIT2_CONSTANT(GIT_INDEXCAP_NO_SYMLINKS);
    PHP_GIT2_CONSTANT(GIT_INDEXCAP_FROM_OWNER);

    // GIT_INDEX_ADD_*
    PHP_GIT2_CONSTANT(GIT_INDEX_ADD_DEFAULT);
    PHP_GIT2_CONSTANT(GIT_INDEX_ADD_FORCE);
    PHP_GIT2_CONSTANT(GIT_INDEX_ADD_DISABLE_PATHSPEC_MATCH);
    PHP_GIT2_CONSTANT(GIT_INDEX_ADD_CHECK_PATHSPEC);

    // GIT_TRACE_*
	PHP_GIT2_CONSTANT(GIT_TRACE_NONE);
    PHP_GIT2_CONSTANT(GIT_TRACE_FATAL);
    PHP_GIT2_CONSTANT(GIT_TRACE_ERROR);
    PHP_GIT2_CONSTANT(GIT_TRACE_WARN);
    PHP_GIT2_CONSTANT(GIT_TRACE_INFO);
    PHP_GIT2_CONSTANT(GIT_TRACE_DEBUG);
    PHP_GIT2_CONSTANT(GIT_TRACE_TRACE);

    // GIT_ATTR_*
    PHP_GIT2_CONSTANT(GIT_ATTR_UNSPECIFIED_T);
    PHP_GIT2_CONSTANT(GIT_ATTR_TRUE_T);
    PHP_GIT2_CONSTANT(GIT_ATTR_FALSE_T);
    PHP_GIT2_CONSTANT(GIT_ATTR_VALUE_T);
    PHP_GIT2_CONSTANT(GIT_ATTR_CHECK_FILE_THEN_INDEX);
    PHP_GIT2_CONSTANT(GIT_ATTR_CHECK_INDEX_THEN_FILE);
    PHP_GIT2_CONSTANT(GIT_ATTR_CHECK_INDEX_ONLY);
    PHP_GIT2_CONSTANT(GIT_ATTR_CHECK_NO_SYSTEM);

    // GIT_STATUS_OPT_*
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_INCLUDE_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_INCLUDE_IGNORED);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_INCLUDE_UNMODIFIED);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_EXCLUDE_SUBMODULES);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_RECURSE_UNTRACKED_DIRS);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_RECURSE_IGNORED_DIRS);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_RENAMES_HEAD_TO_INDEX);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_RENAMES_INDEX_TO_WORKDIR);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_SORT_CASE_SENSITIVELY);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_SORT_CASE_INSENSITIVELY);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_RENAMES_FROM_REWRITES);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_NO_REFRESH);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_UPDATE_INDEX);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_INCLUDE_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_INCLUDE_UNREADABLE_AS_UNTRACKED);
    PHP_GIT2_CONSTANT(GIT_STATUS_OPT_DEFAULTS);

    // GIT_STATUS_SHOW_*
    PHP_GIT2_CONSTANT(GIT_STATUS_SHOW_INDEX_AND_WORKDIR);
    PHP_GIT2_CONSTANT(GIT_STATUS_SHOW_INDEX_ONLY);
    PHP_GIT2_CONSTANT(GIT_STATUS_SHOW_WORKDIR_ONLY);

    // GIT_STATUS_*
    PHP_GIT2_CONSTANT(GIT_STATUS_CURRENT);
    PHP_GIT2_CONSTANT(GIT_STATUS_INDEX_NEW);
    PHP_GIT2_CONSTANT(GIT_STATUS_INDEX_MODIFIED);
    PHP_GIT2_CONSTANT(GIT_STATUS_INDEX_DELETED);
    PHP_GIT2_CONSTANT(GIT_STATUS_INDEX_RENAMED);
    PHP_GIT2_CONSTANT(GIT_STATUS_INDEX_TYPECHANGE);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_NEW);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_MODIFIED);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_DELETED);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_TYPECHANGE);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_RENAMED);
    PHP_GIT2_CONSTANT(GIT_STATUS_WT_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_STATUS_IGNORED);
    PHP_GIT2_CONSTANT(GIT_STATUS_CONFLICTED);
}
