/*
 * php-constants.cpp
 *
 * This file is a part of php-git2.
 */

#include "php-git2.h"
using namespace php_git2;

void php_git2::php_git2_register_constants(int module_number TSRMLS_DC)
{
    // GIT_*
    PHP_GIT2_CONSTANT(GIT_OK);
    PHP_GIT2_CONSTANT(GIT_ERROR);
    PHP_GIT2_CONSTANT(GIT_ENOTFOUND);
    PHP_GIT2_CONSTANT(GIT_EEXISTS);
    PHP_GIT2_CONSTANT(GIT_EAMBIGUOUS);
    PHP_GIT2_CONSTANT(GIT_EBUFS);
    PHP_GIT2_CONSTANT(GIT_EUSER);
    PHP_GIT2_CONSTANT(GIT_EBAREREPO);
    PHP_GIT2_CONSTANT(GIT_EUNBORNBRANCH);
    PHP_GIT2_CONSTANT(GIT_EUNMERGED);
    PHP_GIT2_CONSTANT(GIT_ENONFASTFORWARD);
    PHP_GIT2_CONSTANT(GIT_EINVALIDSPEC);
    PHP_GIT2_CONSTANT(GIT_ECONFLICT);
    PHP_GIT2_CONSTANT(GIT_ELOCKED);
    PHP_GIT2_CONSTANT(GIT_EMODIFIED);
    PHP_GIT2_CONSTANT(GIT_EAUTH);
    PHP_GIT2_CONSTANT(GIT_ECERTIFICATE);
    PHP_GIT2_CONSTANT(GIT_EAPPLIED);
    PHP_GIT2_CONSTANT(GIT_EPEEL);
    PHP_GIT2_CONSTANT(GIT_EEOF);
    PHP_GIT2_CONSTANT(GIT_EINVALID);
    PHP_GIT2_CONSTANT(GIT_EUNCOMMITTED);
    PHP_GIT2_CONSTANT(GIT_EDIRECTORY);
    PHP_GIT2_CONSTANT(GIT_EMERGECONFLICT);
    PHP_GIT2_CONSTANT(GIT_PASSTHROUGH);
    PHP_GIT2_CONSTANT(GIT_ITEROVER);

    // GIT_FEATURE_*
    PHP_GIT2_CONSTANT(GIT_FEATURE_THREADS);
    PHP_GIT2_CONSTANT(GIT_FEATURE_HTTPS);
    PHP_GIT2_CONSTANT(GIT_FEATURE_SSH);
    PHP_GIT2_CONSTANT(GIT_FEATURE_NSEC);

    // GIT_OBJ_*
    PHP_GIT2_CONSTANT(GIT_OBJ_ANY);
    PHP_GIT2_CONSTANT(GIT_OBJ_BAD);
    PHP_GIT2_CONSTANT(GIT_OBJ__EXT1);
    PHP_GIT2_CONSTANT(GIT_OBJ_COMMIT);
    PHP_GIT2_CONSTANT(GIT_OBJ_TREE);
    PHP_GIT2_CONSTANT(GIT_OBJ_BLOB);
    PHP_GIT2_CONSTANT(GIT_OBJ_TAG);
    PHP_GIT2_CONSTANT(GIT_OBJ__EXT2);
    PHP_GIT2_CONSTANT(GIT_OBJ_OFS_DELTA);
    PHP_GIT2_CONSTANT(GIT_OBJ_REF_DELTA);

    // GIT_SORT_*
    PHP_GIT2_CONSTANT(GIT_SORT_NONE);
    PHP_GIT2_CONSTANT(GIT_SORT_TOPOLOGICAL);
    PHP_GIT2_CONSTANT(GIT_SORT_TIME);
    PHP_GIT2_CONSTANT(GIT_SORT_REVERSE);

    // GIT_PATH_LIST_SEPARATOR
    PHP_GIT2_CONSTANT(GIT_PATH_LIST_SEPARATOR);

    // GIT_FILEMODE_*
    PHP_GIT2_CONSTANT(GIT_FILEMODE_UNREADABLE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_TREE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_BLOB);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_BLOB_EXECUTABLE);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_LINK);
    PHP_GIT2_CONSTANT(GIT_FILEMODE_COMMIT);

    // GIT_TREEWALK_*
    PHP_GIT2_CONSTANT(GIT_TREEWALK_PRE);
    PHP_GIT2_CONSTANT(GIT_TREEWALK_POST);
}
